server:
  port: 8080
  host: "localhost"

database:
  host: "xxx.xxx"
  port: 5432
  user: "xxx"
  password: "xxx"
  dbname: "xxx"

redis:
  host: "xxx.xxxx"
  port: 17767
  username: "xxx"
  password: "xxx"
  db: 0

jwt:
  secret: "your-secret-key-here"
  accessExpiry: 24
  refreshExpiry: 168